name: main 

on:
  push:
    branches:
      - 'main'

env:
  TEST_TAG: zhedevops/devops-example-app:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      - run: make compose-test-ci
      - run: make compose-lint-ci

      - name: Build and push app
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: zhedevops/devops-example-app:latest

      - name: Build and push caddy
        uses: docker/build-push-action@v2
        with:
          context: .
          file: services/caddy/Dockerfile
          push: true
          tags: zhedevops/devops-example-caddy:latest
